database:
  host: localhost
  port: 3306
  user: root
  password: yuchao123
  name: finance_system

redis:
  addr: localhost:6379
  password: ""
  db: 0

rabbitmq:
  addr: amqp://guest:guest@localhost:5672/

prometheus:
  port: 2112

logstash:
  addr: localhost:5000

jwt:
  secret_key: yoursecretkey
  expiration_time: 24h

